#platform.team@lge.com	2011.01

obj-$(CONFIG_LGE_BACKLIGHT_LM3530) += backlight_lm3530.o
obj-$(CONFIG_LGE_DISPLAY_MIPI_SHARP_VIDEO_WVGA_PT) += lcd_mipi_sharp.o lcd_mipi_sharp_video_wvga_pt.o
obj-$(CONFIG_LGE_DISPLAY_MIPI_LGIT_VIDEO_HD_PT) += lcd_mipi_lgit.o lcd_mipi_lgit_video_hd_pt.o
