#
# Makefile for the LGE platform device drivers.
#
#platform.team@lge.com	2011.01

EXTRA_CFLAGS += -Iarch/arm/mach-msm
EXTRA_CFLAGS += -Ilge/include
KBUILD_CPPFLAGS += -Ilge/com_device/misc

obj-y += camera/
obj-y += input/
obj-y += misc/
obj-y += display/
obj-y += audio/
#obj-y += power/
obj-y += mhl_v1/
obj-y += device_lge.o

